import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '.next',
      'out',
      'coverage',
      'next-env.d.ts',
      // Generated by `npm run icons`. Never hand-edited. CLAUDE.md §3.
      'src/components/icon/registry.generated.ts',
      'src/components/icon/registry.names.generated.ts',
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,

      // CLAUDE.md §6.
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': 'error',

      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/assets/icons/*', '@/assets/icons/*'],
              message:
                'Import icons through <Icon name="category/name" />, never directly. CLAUDE.md §3.',
            },
            {
              group: ['**/assets/icons-generated/*', '@/assets/icons-generated/*'],
              message:
                'icons-generated/ is a build artefact. Use <Icon name="category/name" />. CLAUDE.md §3.',
            },
          ],
          paths: [
            {
              // Clinical timestamps render in the site's timezone. date-fns
              // formats in the machine's zone, so only src/lib/format.ts may
              // touch it, and it takes an explicit zone at every call.
              name: 'date-fns',
              importNames: ['format', 'parseISO', 'formatISO', 'lightFormat'],
              message:
                "Clinical timestamps render in the site timezone, not the viewer's. Use useSiteFormat(), or src/lib/format.ts outside a component. CLAUDE.md §6.",
            },
          ],
        },
      ],

      // CLAUDE.md §6: no browser storage for record data.
      'no-restricted-globals': [
        'error',
        {
          name: 'localStorage',
          message: 'No localStorage for record data: in-memory only. CLAUDE.md §6.',
        },
        {
          name: 'sessionStorage',
          message: 'No sessionStorage for record data: in-memory only. CLAUDE.md §6.',
        },
      ],
    },
  },
  {
    files: ['src/lib/format.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },
  {
    files: ['scripts/**/*.mjs', '*.config.{mjs,ts}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: globals.node,
    },
    rules: { 'no-console': 'off' },
  },
  {
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.ts'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },
)
